apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineractmysql
  labels:
    app: fineract-server
spec:
  selector:
    matchLabels:
      app: fineract-server
      tier: fineractmysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fineract-server
        tier: fineractmysql
    spec:
      containers:
      - image: mariadb:11.7.2
        name: mysql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fineract-tenants-db-secret
              key: password
        - name: MARIADB_DATABASE
          value: fineract_tenants
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: fineract-tenants-db-secret
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fineract-tenants-db-secret
              key: password
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "2Gi"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -uroot -p${MARIADB_ROOT_PASSWORD}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -uroot -p${MARIADB_ROOT_PASSWORD}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: fineractmysql-pv-claim